# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dygodj0qpQMTcgnvaQH5qc1NSlacfo0h
"""

#1
no_of_input = int(input("Enter the number of inputs : "))
area_of_rectangle ={}
for i in range(no_of_input) :
  user_name = input("Enter the user name : ")
  length = int(input("Enter the length : "))
  width = int(input("Enter the width : "))
  area = length*width
  area_of_rectangle[user_name] = area
print(area_of_rectangle)

#2
no_of_users = int(input("Enter the number of users : "))
body_mass_index = {}
for i in range(no_of_users) :
  user = input("enter the user name : ")
  weight = float(input("enter the weight in kg : "))
  height = float(input("enter the weight in metres : "))
  bmi = round(weight/(height**2),2)
  body_mass_index[user] = bmi
print(body_mass_index)

#3
no_of_students = int(input("enter the number of students : "))
student_dict = {}
for i in range(no_of_students) :
  name = input("Enter the student name : ")
  score1 = input("Enter the score1 : ")
  score2 = input("Enter the score2 : ")
  student_dict[name] = score1,score2
print(student_dict)

#4
no_of_user = int(input("enter the number of users : "))
for i in range(no_of_user):
  user_age = int(input("enter your age : "))
  if user_age < 18 :
    print("Minor")
  elif user_age >= 18 and user_age < 45 :
    print("Adult")
  elif user_age >= 45 :
    print("senior")

#5
for i in range(1,51) :
  if i%2 == 0 :
    print(i)

#6
n = int(input())
for i in range(n) :
  ip = input()
  pswd = input()
  print("the username is"+ip+"The password is"+pswd)

#7
def avg_num(lis1,l1,l2,l3) :
  sum = 0
  lis1.insert(1,l1)
  lis1.insert(2,l2)
  lis1.insert(3,l3)

  for i in range(lis1):
      sum = sum+i
  avg = sum/3
  return sum
  return avg

input1 = int(input("enter the input1 : "))
input2 = int(input("enter the input2 : "))
input3 = int(input("enter the input3 : "))
lis1=[]
print(lis1,avg_num(input1,input2,input3))

#8
def count_vowel(s1) :
  s1.lower()
  count = 0
  for i in range(len(s1)) :
    if s1[i] == 'a' or s1[i] == 'e' or s1[i] == 'i' or s1[i] == 'o' or  s1[i] == 'u' :
      count += 1
    else :
      count = 0
  print(count)


str1 = input()
count_vowel(str1)

#9

import datetime
a = time
b = date
print(a)

#10
i1 = input()
i2 = int(input())
try :
  sum = input1 + input2
  print("sum is "+sum)
except :
  print("To sum the inputs should be integer")

#11
var1 = int(input())
try :
  if var1 > 0 :
    print("yes it is digit")
except ValueError :
  print("The value should be a integer")

#12
num = int(input())
denom = int(input())
try :
  res = num/denom
  print(res)
except ZeroDivisionError:
  print("The denominator should not be zero")

#13
from google.colab import drive
drive.mount('/content/drive')
var_file_1 = open(/content/sample_data/california_housing_train.csv,"w")
var_file_1.write("Hello Python!")
var_file_1.close()

#14
var_file_2 = open(/content/sample_data/california_housing_train.csv,"r") as f1
print(var_file_2.read())
var_file_2.close()

#15
var_file_3 = open(/content/sample_data/california_housing_train.csv,"w")
emp_list=[]
for i in range(3) :
  grp = input()
  emp_list.append(grp)
  var_file_3.writelines(emp_list)
var_file_3.close()

var_file_4 = open(/content/sample_data/california_housing_train.csv,"r") as f1
print(var_file_4.read())
var_file_4.close()